In [ ]:
import pandas as pd

In [ ]:
codes = [
    '6831EEB39C0A5E2F032586CB006834CA',
    'DA9ACE2067B6D9F70325889100482B86',
    '498ACB3ED0593512032588780042D316',
    'C39BA4874DCA1FEF03258854004FBE7D',
    '7C227DFFA0FE78E50325883E00447666',
    '48824D6A4004EBF003258817004F77C7',
    '5D4ED20FA7B6F178032587F900498F9E',
    '1A23678857CF4F52032587DC00470075',
    'DDF4353C1DF6BE83032587C2004A585B',
    '864A1B33089A31DB0325879F0056728F',
    '4BDE097A91DF45B803258782005FB081',
    '1114B9B7DA3B591403258782005FB1D3',
    '83B9F1F2431ED38D03258765006CE725',
    '3B2764763A9691BF0325874400692B85',
    'DC78EF599B10BE7903258725005C5160',
    'F193D9F12D43274703258705006CCE72',
    '79123FCF710FEC8A032586EA0069857B',
    '3163BDF9D27173D2032586CB00623F0F',
    '147313FE0361E06B03258565006E0978',
    '05E1B317C330ACAF0325869D00469D7D',
    '9C581938DAD46CAF03258673004A67D2',
    'ABB10A0B4CE5263303258656005BD2BC',
    'B701441666FD2ADA03258633004EC56B',
    '8F70D1DBF34A8B230325861A007847B9',
    'D7FC309698ECD721032585F400492002',
    '6B2BEC32A2AC7609032585D600637E14',
    '1A88FD41AF110100032585BB0069837B',
    '94B8BA65F067A0A30325859E006B26EA',
    'BF5A48FC55F0A62A0325857B004EB46A',
    '58B5C36D3B93EF22032585650075ACB9',
    '58B5C36D3B93EF22032585650075ACB9',
    '2A1019DE2CCBCB7C032583940066DE7F',
    '13EE2193D92C6D9403258523004AE924',
    'F0C98543ABD90DC80325850600481B25',
    '1261EE2257A16481032584E900530B33',
    'B0FE4368C6C172F8032584CB00649720',
    '44A37B73E63E1115032584A500542D53',
    '3B6FC33B0E73C5130325848C004CFA42',
    '9525DA3A9CD48ED70325846A00470728',
    'AD1D25671460A0E6032584560053582E',
    '85F639A05371E6260325842D004C4C1F',
    '3928A200C6E71527032584160069DB4C',
    'DB84A982895EEC06032583EF0054B3C7',
    'BE0CB7B5CD2191FD032583DA0047B36C',
    'C0F1BC89F80A5F94032583B50066FBB9',
    '86BEB5538808F8A7032583670049BF64',
    '45AE7393B899A89F032583930062E254',
    'B54FE7659BDBB1E4032583670049B786',
    '3F0E75E6CB310948032582A9005312AF',
    '3779AB395FFB47CF032583670049C75B',
    '9AACFC92A1900FA6032582EC00745AA9',
    '0391BC84DFE8176D032582E800501696',
    '5F5ED1FC8B1AF22C032582CE004A4A68',
    '5F38C9C3B1560E2A032582A900530FD8',
    '40567C3D6B9FAC70032582A900530A5A',
    '0BCAEE58E935AB080325823B0068CC17',
    '971D78FC51FE954C032582A900531487',
    '5C923AF9F888C6640325823B00629CF4',
    '1F06D954FDA5F6240325823B00683FB6',
    '1B76BA8918E47FA1032581A000638B4A',
    '1B76BA8918E47FA1032581A000638B4A',
    'EDB58FB48233BF06032581A0006383C5',
    '59148E4DEEE5AC240325823B005E235D',
    'EED4B091C8BE82A00325823B005E2D48',
    '383FBD9920D428F40325823B005E0E5E',
    '7B769CFFBA7814340325823B005E1B35',
    '0A852DD6B52020210325823B005E0586',
    '6AF8AC5349E1B30C0325823B005E010F',
    '1BB8B0755011F7FC0325823B005DF41F',
    '376AFD2D2D8BD45E0325823B005DEBE6',
    '7B1D6DBE45E5B3B40325823B005DDDBD',
    'A2B4DEF2146319260325823B005DE1DA',
    '4D7DC8D672D851880325823B005DD4F6',
    'CA083D66854DE2B70325823B005DCF81',
    '126AB1BA5E8C38E90325823B005DC11A',
    'F9E77AACD7C142A80325823B005DC8CC',
    'D54B100C66AB5DBA0325823B005D9C75',
    'EBB62CFB43C5A52C0325823B005D9180',
    '0AA7F748AD9D441A032581F7007200D2',
    'C3B40DCC3DF3EDE7032581F700723CEF',
    '0E295D74D1F6EEF503258100007403D5',
    'F3445D62ABDACAF50325810000740207',
    '02AAA1FBEE58DF4D032581000073FF51',
    '5382B612B48FC07E032581000073FE4C',
    '3F43DA5BE61ED68B032581000073FD1A',
    '4FD2174F2E58B221032581000073FB75',
    'F006DDAA5F3D96EB032581000073FA77',
    '67C580E66A89F871032581000073F8EB',
    'C35EF31C18D6D5B1032581000070BB18',
    'E911AA393583946A032581000074075A',
    'E911AA393583946A032581000074075A',
    'CE4589B52A8D25BC0325810000740622',
    '025C6EEB3DF658D8032581000074050E',
    '0FF802D0D871909F0325808700638AD1',
    '9F9E646CEEEA456803257F63004D0C33',
    '9D387E66E681520003257F640056D41D',
    '10BA3BDD0C205E8C03257F640056E81A',
    '3EC4B1D80551042903257F640056D1E9',
    '07D74FB7FCE8472903257F030067D7DF',
    '58F95CA2C6962E5703257F030067D4E1',
    'AE2BCFB3BE59B30D03257F030067D3B8',
    'F81DD593EC9F6FEF03257F030067CEDB',
    'B485F275E17D3E1503257F030067D03A',
    'BF269D21C82C832E03257DD90066C141',
    '8288E2909C27597E03257F030067CB92',
    '8A11B2C21DF8B1A903257F030067DD8D',
    '01F3C4E12E39C3E603257F030067D90A',
    '21CDB8B721EA7E1803257F030067D264',
    'C535384CC3E0B2F303257DD90066D624',
    'C8A020F957DF4B2C03257DD90066BE1D',
    '6518885242C80C2103257B580063DDD7',
    '2BC387B8383F5B5903257D80004FBA99',
    '8E28614654B48F6303257D80004FBBDE',
    '1BBD9DF9857A616803257D80004FBCD8',
    'F0944D558A37839D03257D80004FBDFD',
    'CD91CA303CDFB9A203257D80004FCA2D',
    'B348626AFFB7EDFD03257D80004FBEF0',
    '6EF218A51570D45803257D80004FC00F',
    'C871855DDFECE28903257D80004FC3B6',
    'DFFF717FA1E97B0E03257D80004FB997',
    'DFFF717FA1E97B0E03257D80004FB997',
    '15D845BB5AD5898F03257D80004F9C4D',
    'D9F48104FC4E28DF03257D80004FA20C',
    'B12657594AD4F1BA03257D80004F91E6',
    '412535E15545413003257AA700439272',
    '2C6164EB1E680CC703257D80004F6E9C',
    '3481DDFD390535CE03257BBB004A380A',
    'C460471B80CF0AF103257BBB004A593E',
    '3AB5B095EBC0405203257D80004F86A3',
    '5E305EEEA54D34B903257BBB0049EED0',
    'B37B8D7E48DE648703257B580063D7B9',
    '024B8A74FBF70D288325757E0050AAAA',
    '68767C0E317945BB03257B580063E423',
    '8ECA3E3BBB4E7A1B03257B580063CCC9',
    '19865852DD3DC02603257B580063BBAB',
    '73423D8D885D858C03257AB40050EAE4',
    '1D814583BD60B28703257912004CEB1C',
    'ECD9B48E3B62CD0B03257BBB004A71F3',
    'E821F1F7D70DCB1A032578CE004D3774',
    '1AF001C2CA29C2E403257AA700436B51',
    '15C864FBA57CBB9303257AA700439CC7',
    'DD2798AF29B44F1B03257AA600738564',
    '721821E690D4480903257AA600737EAD',
    '25CEDD2E0E229D1C03257AA600737526',
    'D62FCA02DBE815A303257AA600736E19',
    '6BF46EEE7C628C4103257AA60073605B',
    'EC23F3E24628227403257AA6006F782C',
    '25DEEC6BF1F3D8440325794100537860',
    'DD4A116B8274B9D00325779D006E421D',
    '2C95B9C0758DF36103257AA70043763A',
    '2C95B9C0758DF36103257AA70043763A',
    '972F2AB5B28AC9358325761F0047953C',
    '3D5E1220589DBB4403257AA6007390B5',
    '161245F7A44B88D30325794100536F7D',
    'DEC935FAA119DA840325788F0050F0AE',
    '33F3A543C220CD0C03257876004B9AF9',
    'C28F81F426633E6B032578560072153A',
    '098DD756FA0EF6320325783800690D5A',
    '6381AAE1FAC04E1703257810004982CD',
    '7DE10AF8474EEBD20325781000497BA3',
    'E952DA3E4273C461032577D5004EB0DA',
    '37DC4348CB5E1F4D032577BD00528A4D',
    'B631A4AE13E38277032578EA00521A6B',
    '175B909391ECD97C0325773B004CF8C2',
    '8D580A9BA16D1DF0032577570052C584',
    '30B9DE2C740E3E878325761E00534D64',
    '7BDFF564E65013190325771A0043DA18',
    'EE75970F22BCDB38032576F50073FAE0',
    '36591DAA5B07838D032576D9004AAA4A',
    '17C13C46DD31E154032576BD0054B843',
    '5DF6BC5EE58C4A8C032576A300725A73',
    '2B0425BB75EDB5B30325767F004A11E6',
    '79CA10A4ABF19DF70325766A004EC479',
    '8EF0BAA5FF5121A38325760F0051756B',
    'DFFE1926EA87DF210325777A006BD58B',
    '08F8DD77120D1D2183257624005398F9',
    'D142395D4A9CD03A032578B70067EB4B',
    '25EF86BFFA56E0DB0325766A004EBB85',
    'A812666288828AC5832575E4004A1C1B',
    '1CA7DE24877778BB832575AE00568DEA',
    '1CA7DE24877778BB832575AE00568DEA',
    '92A9175460784A21832575AE005684F5',
    'E4CBBAB73C348DF58325757E0050F456',
    'A9C3FE6B2D5E45048325757E0050EA34',
    '95571C327A608EE2032577BD0052A372',
    'EDE0B0784D3ADDC48325752E006CC160',
    '4D8976DD40EA305D83257513004FB7FA',
    'D41297A217ABC1AF83257513004EFA3D',
    '705F59A89C2AD823032574B900611E5F',
    '183AE350B146CC74032574B90057D847',
    'E779AF86132B5CA7032574B9005490AE',
    '5E38CDCAE33FA0A7032574B8006CD27A',
    'B23580522BECA300032574B8006C5D08',
    'D20ADF266FB2BBCD032574B8006BE0E7',
    '2205F4C67BD23670032574B8006B71B4',
    'E5926D95DCA3DC00032574B80069EB19',
    '5CCE029CC71839E7032574B8006937F3',
    '87C16A563DF7E23E032574B80068F333',
    '92F7B91E8F382C8E032574B80068C072',
    '5518C72A65141BAB032574B800679A47',
    'AEF416A1F4FAADB0032574B800673403',
    'A625AEFEA25F4318032574B800702DB1',
    '725E7EDAC3A4F2500325749E0050CBA1',
    '3922B20C40A0B037032572BA00581083',
    'DCB66FB9CF9613760325729100626776',
    'A0CC06AC1E2AD214032572910057C1CC',
    '6DA3A4259423CC0A0325727C005610CF',
    '27A9E974DAFB67B80325723D004C6EA2',
    '6A141E444DF38F5E032572200057DC08',
    '78672AC38AA93759032571FB004C85AD',
    '78672AC38AA93759032571FB004C85AD',
    '0251C4CCFA3D4666032571F80075B55A',
    '587E67E0628F7FA3032571F8007598D7',
    '7FFF19CAA4E1B28B032571B70073F8B2',
    'E1F914165BFCA804032571B70073E600',
    '615900AC08407C430325717A006B4861',
    '2E39BD1E734C1C210325717A006AB598',
    'C3508285FA7F2A9C032571380072C704',
    '967BA15F014600C003257138007296D9',
    '356A760F760774300325713800726A6A',
    '5A69C7EBB0629C67032570DF0065C966',
    'C008D19FDD87E8C4032570DF00659359',
    '5EA58FFB19C2E3FB032570DF00656959',
    '5EBEE907D7051B1A032570DF00652B35',
    '27C396380C8C804B0325706E004BC6E7',
    'F09A4F807E28C4820325706E004B8BE4',
    '98C152D59920A7DB0325706E004B49AE',
    '3D65B633F6F5BE7A0325706E004852DA',
    '86212B82EE6B04B90325706E004809EF',
    'F1E316D4AE9B50710325706E0047BF3F',
    '1E416B540ADF85690325706E00457B74',
    'A6E175349541ED9D0325706D0067D845',
    '52D493B04B6BD23703256F900057BEEC',
    '2927EBFA15F6E03103256F9000578F3C',
    'AF49919374A7C96003256F160069B450',
    '3E29560083FA04E603256F1600683EA3',
    '06DD88160F91420403256F1600535071',
    'C72D99093FC4A91003256F16005317AC',
    'F0B6F86B815D4E7C03256F160052B875',
    '95B9FA8DDE99B5F203256F160051E36C',
    '95B9FA8DDE99B5F203256F160051E36C',
    '65E216F5390D6E8E03256E5500728C54',
    '1F90090D06DCE5ED03256E550071DF0D',
    '1B1AC4DE889F062303256E550073154A',
    '0F564C1494E229EC03256CD8004DE65C',
    '61EF8E641A3DDBF703256CD8004DFD04',
    '833F054AA38C87A803256CD2004E13AB',
    'A259BAD22C8A80B403256C750074B0D0',
    'B7ECCEDABFD2596A03256C15007064F5',
    'AA83C01DB44CC8F703256C15007054F2',
    'BE045D20C63A383703256C1500703C05',
    '47A361291474B95503256BE6004BA98F',
    '8F674B801213881A03256BE6004B9BA4',
    '8102B0E14E81328303256BE6004B8BD0',
    '7319740813D32BAF03256B76004E50FB',
    '3D20285D7F9BE6D203256B76004E3D78',
    '5CFB738F8D74E5C203256B76004DE724',
    'E7D14E5E9A2AF75B03256AFE00792983',
    '6889725B188F95FD03256AFE00791C01',
    'A8951D525BCC59C703256AFE00790A60',
    '3B04A21DDCAB22E903256AA80047BE56',
    '4D31F860AEF79F0A03256AA800478E68',
    '8059DFA4F962CFBA03256AA800477148',
    '768AE87F169E05E803256A4C00796986',
    'D9ADB756A292E4A003256A4C00794972',
    '059987073095A57303256A4C007927FC',
    'C91032042969071F032569F90057ACF5',
    '2693F99EC776C1A0032569F9005785A5',
    'EC4662F7F0EBC024032569F9005760BC',
    '4CBB56FFA76487C00325699A006395F7',
    '4CBB56FFA76487C00325699A006395F7',
    '9B369F70DAD041390325699A00637948',
    '07E8944549D3F6A40325699A00633170',
    '8E0BF9FAFE7F7F300325693B00583C08',
    '3485472AB264FD490325693B00580015',
    '07AA22F2481669C40325693B0057BEB5',
    'ECC400C7FEE7B709032568E00074D8A9',
    'C9159D33E9E98604032568E00074AE91',
    '19EA496287EA89AD032568E00071AA5D',
    '01D773F6D48D3666032568810059CF8E',
    'CA0257C12BDBF7F10325688100599F85',
    '858744640BFA92E60325688100594090',
    '67FDA9A7A1D1DC01032574B8006658B0',
    'D8D415BB2A53880103256826004D5E04',
    '9C0DC0C31EF8619803256826004D34E2',
    'BE9AF3B04B73E0CC03256826004D01E1',
    '96002B78194346CE032567D000751B19',
    '6A07C952795EF477032567D00074FC65',
    '2DBC72A2E0DB40AE032567D00074C989',
    '75B6F0534F2256B80325676D00734A40',
    'CB97F151A6EC1D100325676D00732483',
    '2A9A3FDE137DF8330325676D0072EC8B',
    'E0A897356B99A44A0325671D006DC0AC',
    'C9EF24C379D6E5D00325671D006DA280',
    '6227591362B1D3070325671A0051EFB3',
    'F0E1319167C43C42032566BB006AEEA6',
    '4AA54661F7E1D540032566BB006934DC',
    '9BEE5441C9BA98BE032566BB006703A9',
    'FE996E511763FBC103256665004B6D6C',
    '123941FFCEEECE9703256665004B501D',
    '123941FFCEEECE9703256665004B501D',
    '180DC782BAF8F52303256665004B322B',
    '08581F5944C926FE032565FE004E8F74',
    '2EA36C38259C2CE9032565FE004E71FF',
    '3893E2E506789B1A032565FE004E58F1',
    '7E1BB2FC48C83F9A032565A8006833D3',
    'A8F8C473860EF659032565A80067EB58',
    '9C58C23675E98802032565A80067BB48',
    '7DFDC6B1B6152F79032566BB006A2A87',
    '86DA79AA6D4A742B8625654E00003C77',
    'C437D8D96086E5D38625654D0083D1F3',
    'E4520D19348F674E8625654D007AA951',
    'FE390993F441606C862564F00078C74F',
    'E90B1C3B1E667ED2862564F00077EC15',
    'B2877696DF6130B4862564F000765292',
    '51CFACFCA110D97B8625649200632DD4',
    '4EAB2DEB7D44614D862564920061C3AF',
    '4BEA5AE7C779655B8625649200626499',
    'D52C8620884ABFE986256442005820B1',
    '37CD4C8D55FFE7B7862564420057B3EA',
    '162C0FF4DB6765DC86256441007CC416',
    '0B6DB429292657768625642800596752',
    '3A1D53368420DCC686256428005966FA',
    '10F5374EBFF8FE3086256428005964A9',
    'AEFFCDE7C7980B6C862564280058FDE4',
    '732951C51CD06F01862564280058FD71',
    'DE953B075A4FF0C88625642800588474',
    '92FE4DD5C60D3E9586256428005837B6',
    '737509EEF42EB0928625642800583753',
    'EFAB3FAA731B130F86256428005835B7',
    'EFAB3FAA731B130F86256428005835B7',
    'B2E2643A75C023DC862564280057E06E',
    '16D4A9EB8B8D1C3A862564280057E005',
    '124CB5DF3B73003F862564280057DDAF',
    '3C874D15A02FA95C862564280004159F',
    '200096A8161C54A18625642800041537',
    'E146A5E5FD9D566F8625642800041338'
]

In [ ]:
months = [
    '08-2022',
    '07-2022',
    '06-2022',
    '05-2022',
    '04-2022',
    '03-2022',
    '02-2022',
    '01-2022',
    '12-2021',
    '11-2021',
    '10-2021',
    '09-2021',
    '09-2021',
    '08-2021',
    '07-2021',
    '06-2021',
    '05-2021',
    '04-2021',
    '03-2021',
    '02-2021',
    '01-2021',
    '12-2020',
    '11-2020',
    '10-2020',
    '09-2020',
    '08-2020',
    '07-2020',
    '06-2020',
    '05-2020',
    '04-2020',
    '04-2020',
    '03-2020',
    '02-2020',
    '01-2020',
    '12-2019',
    '11-2019',
    '10-2019',
    '09-2019',
    '08-2019',
    '07-2019',
    '06-2019',
    '05-2019',
    '04-2019',
    '03-2019',
    '02-2019',
    '01-2019',
    '12-2018',
    '11-2018',
    '10-2018',
    '09-2018',
    '08-2018',
    '07-2018',
    '06-2018',
    '05-2018',
    '04-2018',
    '03-2018',
    '02-2018',
    '01-2018',
    '12-2017',
    '11-2017',
    '11-2017',
    '11-2017',
    '10-2017',
    '10-2017',
    '09-2017',
    '09-2017',
    '08-2017',
    '08-2017',
    '07-2017',
    '07-2017',
    '06-2017',
    '06-2017',
    '05-2017',
    '05-2017',
    '04-2017',
    '04-2017',
    '03-2017',
    '03-2017',
    '02-2017',
    '02-2017',
    '01-2017',
    '12-2016',
    '11-2016',
    '10-2016',
    '09-2016',
    '08-2016',
    '07-2016',
    '06-2016',
    '05-2016',
    '04-2016',
    '04-2016',
    '03-2016',
    '02-2016',
    '02-2016',
    '02-2016',
    '01-2016',
    '12-2015',
    '11-2015',
    '10-2015',
    '09-2015',
    '08-2015',
    '07-2015',
    '06-2015',
    '05-2015',
    '04-2015',
    '03-2015',
    '02-2015',
    '01-2015',
    '12-2014',
    '11-2014',
    '10-2014',
    '09-2014',
    '08-2014',
    '07-2014',
    '06-2014',
    '05-2014',
    '04-2014',
    '03-2014',
    '02-2014',
    '01-2014',
    '01-2014',
    '12-2013',
    '11-2013',
    '10-2013',
    '09-2013',
    '08-2013',
    '07-2013',
    '06-2013',
    '05-2013',
    '04-2013',
    '03-2013',
    '02-2013',
    '01-2013',
    '12-2012',
    '11-2012',
    '10-2012',
    '09-2012',
    '08-2012',
    '07-2012',
    '06-2012',
    '05-2012',
    '04-2012',
    '03-2012',
    '02-2012',
    '01-2012',
    '12-2011',
    '11-2011',
    '10-2011',
    '09-2011',
    '08-2011',
    '08-2011',
    '07-2011',
    '06-2011',
    '05-2011',
    '04-2011',
    '03-2011',
    '02-2011',
    '01-2011',
    '12-2010',
    '11-2010',
    '10-2010',
    '09-2010',
    '08-2010',
    '07-2010',
    '06-2010',
    '05-2010',
    '04-2010',
    '03-2010',
    '02-2010',
    '01-2010',
    '12-2009',
    '11-2009',
    '10-2009',
    '09-2009',
    '08-2009',
    '07-2009',
    '06-2009',
    '05-2009',
    '04-2009',
    '03-2009',
    '03-2009',
    '02-2009',
    '01-2009',
    '12-2008',
    '11-2008',
    '10-2008',
    '09-2008',
    '08-2008',
    '07-2008',
    '06-2008',
    '05-2008',
    '04-2008',
    '03-2008',
    '02-2008',
    '01-2008',
    '12-2007',
    '11-2007',
    '10-2007',
    '09-2007',
    '08-2007',
    '07-2007',
    '06-2007',
    '05-2007',
    '04-2007',
    '03-2007',
    '02-2007',
    '01-2007',
    '12-2006',
    '11-2006',
    '10-2006',
    '10-2006',
    '09-2006',
    '08-2006',
    '07-2006',
    '06-2006',
    '05-2006',
    '04-2006',
    '03-2006',
    '02-2006',
    '01-2006',
    '12-2005',
    '11-2005',
    '10-2005',
    '09-2005',
    '08-2005',
    '07-2005',
    '06-2005',
    '05-2005',
    '04-2005',
    '03-2005',
    '02-2005',
    '01-2005',
    '12-2004',
    '11-2004',
    '10-2004',
    '09-2004',
    '08-2004',
    '07-2004',
    '06-2004',
    '05-2004',
    '05-2004',
    '04-2004',
    '03-2004',
    '02-2004',
    '01-2003',
    '01-2003',
    '12-2002',
    '11-2002',
    '10-2002',
    '09-2002',
    '08-2002',
    '07-2002',
    '06-2002',
    '05-2002',
    '04-2002',
    '03-2002',
    '02-2002',
    '01-2002',
    '12-2001',
    '11-2001',
    '10-2001',
    '09-2001',
    '08-2001',
    '07-2001',
    '06-2001',
    '05-2001',
    '04-2001',
    '03-2001',
    '02-2001',
    '01-2001',
    '01-2001',
    '12-2000',
    '11-2000',
    '10-2000',
    '09-2000',
    '08-2000',
    '07-2000',
    '06-2000',
    '05-2000',
    '04-2000',
    '03-2000',
    '02-2000',
    '01-2000',
    '01-2000',
    '12-1999',
    '11-1999',
    '10-1999',
    '09-1999',
    '08-1999',
    '07-1999',
    '06-1999',
    '05-1999',
    '04-1999',
    '03-1999',
    '02-1999',
    '01-1999',
    '12-1998',
    '11-1998',
    '10-1998',
    '09-1998',
    '09-1998',
    '08-1998',
    '07-1998',
    '06-1998',
    '05-1998',
    '04-1998',
    '03-1998',
    '02-1998',
    '01-1998',
    '01-1998',
    '12-1997',
    '11-1997',
    '10-1997',
    '09-1997',
    '08-1997',
    '07-1997',
    '06-1997',
    '05-1997',
    '04-1997',
    '03-1997',
    '02-1997',
    '01-1997',
    '12-1996',
    '11-1996',
    '10-1996',
    '09-1996',
    '08-1996',
    '07-1996',
    '06-1996',
    '05-1996',
    '05-1996',
    '04-1996',
    '03-1996',
    '02-1996',
    '01-1996',
    '12-1995',
    '11-1995'
]

In [ ]:
data = {a:b for a, b in zip(months, codes)}
data

In [ ]:
URL = f'https://www.enre.gov.ar/web/Tarifasd.nsf/todoscuadros/CODE?opendocument'
urls = [URL.replace('CODE', code) for code in codes]

def get_row(page, month, idx):
    types  = page[0][idx-1].values
    units  = page[1].values
    values = page[idx].values
    return {
        'month'             : month,
        'empresa'           : values[0],
        'type'              : types[0],   
        'cargo_fijo_unidad' : units[1],
        'cargo_fijo'        : float(values[1]),
        'cargo_var_unidad'  : units[2],
        'cargo_var'         : float(values[2])
    }

def get_rows(page, month, indexes):  return [get_row(page, month, idx)for idx in indexes]

In [ ]:
data1 = {
    '08-2022': '6831EEB39C0A5E2F032586CB006834CA',
    '07-2022': 'DA9ACE2067B6D9F70325889100482B86',
    '06-2022': '498ACB3ED0593512032588780042D316',
    '05-2022': 'C39BA4874DCA1FEF03258854004FBE7D',
    '04-2022': '7C227DFFA0FE78E50325883E00447666',
    '03-2022': '48824D6A4004EBF003258817004F77C7',
    '02-2022': '5D4ED20FA7B6F178032587F900498F9E',
    '01-2022': '1A23678857CF4F52032587DC00470075',
    '12-2021': 'DDF4353C1DF6BE83032587C2004A585B',
    '11-2021': '864A1B33089A31DB0325879F0056728F',
    '10-2021': '4BDE097A91DF45B803258782005FB081',
    '09-2021': '83B9F1F2431ED38D03258765006CE725',
    '08-2021': '3B2764763A9691BF0325874400692B85',
    '07-2021': 'DC78EF599B10BE7903258725005C5160',
    '06-2021': 'F193D9F12D43274703258705006CCE72',
    '05-2021': '79123FCF710FEC8A032586EA0069857B',
    '04-2021': '3163BDF9D27173D2032586CB00623F0F',
    '03-2021': '147313FE0361E06B03258565006E0978',
    '02-2021': '05E1B317C330ACAF0325869D00469D7D',
    '01-2021': '9C581938DAD46CAF03258673004A67D2',
    '12-2020': 'ABB10A0B4CE5263303258656005BD2BC',
    '11-2020': 'B701441666FD2ADA03258633004EC56B',
    '10-2020': '8F70D1DBF34A8B230325861A007847B9',
    '09-2020': 'D7FC309698ECD721032585F400492002',
    '08-2020': '6B2BEC32A2AC7609032585D600637E14',
    '07-2020': '1A88FD41AF110100032585BB0069837B',
    '06-2020': '94B8BA65F067A0A30325859E006B26EA',
    '05-2020': 'BF5A48FC55F0A62A0325857B004EB46A',
    '04-2020': '58B5C36D3B93EF22032585650075ACB9',
    '03-2020': '2A1019DE2CCBCB7C032583940066DE7F',
    '02-2020': '13EE2193D92C6D9403258523004AE924',
    '01-2020': 'F0C98543ABD90DC80325850600481B25',
    '12-2019': '1261EE2257A16481032584E900530B33',
    '11-2019': 'B0FE4368C6C172F8032584CB00649720',
    '10-2019': '44A37B73E63E1115032584A500542D53',
    '09-2019': '3B6FC33B0E73C5130325848C004CFA42',
    '08-2019': '9525DA3A9CD48ED70325846A00470728',
    '07-2019': 'AD1D25671460A0E6032584560053582E',
    '06-2019': '85F639A05371E6260325842D004C4C1F',
    '05-2019': '3928A200C6E71527032584160069DB4C',
    '04-2019': 'DB84A982895EEC06032583EF0054B3C7',
    '03-2019': 'BE0CB7B5CD2191FD032583DA0047B36C',
    '02-2019': 'C0F1BC89F80A5F94032583B50066FBB9',
    '01-2019': '86BEB5538808F8A7032583670049BF64',
    '12-2018': '45AE7393B899A89F032583930062E254',
    '11-2018': 'B54FE7659BDBB1E4032583670049B786',
    '10-2018': '3F0E75E6CB310948032582A9005312AF',
    '09-2018': '3779AB395FFB47CF032583670049C75B',
    '08-2018': '9AACFC92A1900FA6032582EC00745AA9',
    '07-2018': '0391BC84DFE8176D032582E800501696',
    '06-2018': '5F5ED1FC8B1AF22C032582CE004A4A68',
    '05-2018': '5F38C9C3B1560E2A032582A900530FD8',
    '04-2018': '40567C3D6B9FAC70032582A900530A5A',
    '03-2018': '0BCAEE58E935AB080325823B0068CC17',
    '02-2018': '971D78FC51FE954C032582A900531487',
    '01-2018': '5C923AF9F888C6640325823B00629CF4',
    '12-2017': '1F06D954FDA5F6240325823B00683FB6'
 }

In [ ]:
rows = []

for month, code in data1.items():
    url = URL.replace('CODE', code)
    page = pd.read_html(url)

    try:
        rows.extend(get_rows(page[5], month, [2, 3]))
    except:
        print('Error:', month, code)

df = pd.DataFrame(rows)

In [ ]:
df

,month,empresa,type,cargo_fijo_unidad,cargo_fijo,cargo_var_unidad,cargo_var
0,08-2022,EDENOR,Tarifa 1 -R6,$/mes,622.72,$/kWh,4.898
1,08-2022,EDESUR,Tarifa 1 -R6,$/mes,597.55,$/kWh,4.879
2,07-2022,EDENOR,Tarifa 1 -R6,$/mes,622.72,$/kWh,4.898
3,07-2022,EDESUR,Tarifa 1 -R6,$/mes,597.55,$/kWh,4.879
4,06-2022,EDENOR,Tarifa 1 -R6,$/mes,622.72,$/kWh,4.898
...,...,...,...,...,...,...,...
109,02-2018,EDESUR,Tarifa 1 -R6,$/mes,292.80,$/kWh,1.735
110,01-2018,EDENOR,Tarifa 1 -R6,$/mes,270.59,$/kWh,1.507
111,01-2018,EDESUR,Tarifa 1 -R6,$/mes,285.39,$/kWh,1.548
112,12-2017,EDENOR,Tarifa 1 -R6,$/mes,270.59,$/kWh,1.507
113,12-2017,EDESUR,Tarifa 1 -R6,$/mes,285.39,$/kWh,1.548

In [ ]:
df.to_csv('file1.csv')

In [ ]:
data2 = {
    '11-2017': 'EDB58FB48233BF06032581A0006383C5',
    '10-2017': 'EED4B091C8BE82A00325823B005E2D48',
    '09-2017': '7B769CFFBA7814340325823B005E1B35',
    '08-2017': '6AF8AC5349E1B30C0325823B005E010F',
    '07-2017': '376AFD2D2D8BD45E0325823B005DEBE6',
    '06-2017': 'A2B4DEF2146319260325823B005DE1DA',
    '05-2017': 'CA083D66854DE2B70325823B005DCF81',
    '04-2017': 'F9E77AACD7C142A80325823B005DC8CC',
    '03-2017': 'EBB62CFB43C5A52C0325823B005D9180',
    '02-2017': 'C3B40DCC3DF3EDE7032581F700723CEF'
}

In [ ]:
rows2 = []

for month, code in data2.items():
    url = URL.replace('CODE', code)
    page = pd.read_html(url)

    try:
        rows2.extend(get_rows(page[5].iloc[1:, :], month, [2, 3]))
    except:
        print('Error:', month, code)

df2 = pd.DataFrame(rows2)
df2

,month,empresa,type,cargo_fijo_unidad,cargo_fijo,cargo_var_unidad,cargo_var
0,11-2017,EDENOR,Tarifa 1 -R6,$/mes.,198.40,$/kWh,1.073
1,11-2017,EDESUR,Tarifa 1 -R6,$/mes.,220.75,$/kWh,1.119
2,10-2017,EDENOR,Tarifa 1 -R6,$/bim.,79.36,$/kWh,0.464
3,10-2017,EDESUR,Tarifa 1 -R6,$/bim.,88.30,$/kWh,0.511
4,09-2017,EDENOR,Tarifa 1 -R6,$/bim.,79.36,$/kWh,0.464
5,09-2017,EDESUR,Tarifa 1 -R6,$/bim.,88.30,$/kWh,0.511
6,08-2017,EDENOR,Tarifa 1 -R6,$/mes.,198.40,$/kWh,1.073
7,08-2017,EDESUR,Tarifa 1 -R6,$/mes.,220.75,$/kWh,1.119
8,07-2017,EDENOR,Tarifa 1 -R6,$/mes.,198.40,$/kWh,1.073
9,07-2017,EDESUR,Tarifa 1 -R6,$/mes.,220.75,$/kWh,1.119
10,06-2017,EDENOR,Tarifa 1 -R6,$/bim.,79.36,$/kWh,0.464
11,06-2017,EDESUR,Tarifa 1 -R6,$/bim.,88.30,$/kWh,0.511
12,05-2017,EDENOR,Tarifa 1 -R6,$/mes.,198.40,$/kWh,1.073
13,05-2017,EDESUR,Tarifa 1 -R6,$/mes.,220.75,$/kWh,1.119
14,04-2017,EDENOR,Tarifa 1 -R6,$/bim.,79.36,$/kWh,0.464
15,04-2017,EDESUR,Tarifa 1 -R6,$/bim.,88.30,$/kWh,0.511
16,03-2017,EDENOR,Tarifa 1 -R6,$/bim.,79.36,$/kWh,0.464
17,03-2017,EDESUR,Tarifa 1 -R6,$/bim.,88.30,$/kWh,0.511
18,02-2017,EDENOR,Tarifa 1 -R6,$/bim.,79.36,$/kWh,0.402
19,02-2017,EDESUR,Tarifa 1 -R6,$/bim.,88.30,$/kWh,0.449

In [ ]:
df2.to_csv('file2.csv')

In [ ]:
p =pd.read_html('https://www.enre.gov.ar/web/Tarifasd.nsf/todoscuadros/3F43DA5BE61ED68B032581000073FD1A?opendocument')

In [ ]:
p[1]

                           0       1       2       3       4
0              Tarifa 1 - R2     NaN  EDESUR  EDENOR  EDELAP
1         Cargo Fijo 301-650  $/bim.   60.14   54.46     NaN
2     Cargo Variable 301-650   $/kWh   0.459   0.448     NaN
3         Cargo Fijo 651-800  $/bim.   71.68   66.14     NaN
4     Cargo Variable 651-800   $/kWh   0.479   0.469     NaN
5         Cargo Fijo 801-900  $/bim.   78.76   72.29     NaN
6     Cargo Variable 801-900   $/kWh   0.492   0.480     NaN
7        Cargo Fijo 901-1000  $/bim.   84.34   81.16     NaN
8    Cargo Variable 901-1000   $/kWh   0.502   0.496     NaN
9       Cargo Fijo 1001-1200  $/bim.  133.32  115.65     NaN
10  Cargo Variable 1001-1200   $/kWh   0.589   0.557     NaN
11      Cargo Fijo 1201-1400  $/bim.  148.43  131.64     NaN
12  Cargo Variable 1201-1400   $/kWh   0.616   0.586     NaN
13      Cargo Fijo 1401-2800  $/bim.  148.43  131.64     NaN
14  Cargo Variable 1401-2800   $/kWh   0.616   0.586     NaN
15         Cargo Fijo + 2800  $/bim.  148.43  131.64     NaN
16     Cargo Variable + 2800   $/kWh   0.616   0.586     NaN

In [ ]:
def get_row(page, month, idx):
    types  = page[0].values
    units  = page[1].values
    values = page[idx].values
    return {
        'month'             : month,
        'empresa'           : values[0],
        'type'              : types[0],   
        'cargo_fijo_unidad' : units[1],
        'cargo_fijo'        : float(values[1]),
        'cargo_var_unidad'  : units[2],
        'cargo_var'         : float(values[2])
    }

In [ ]:
get_rows(www, 'month', [2, 3])

[{'month': 'month',
  'empresa': 'EDESUR',
  'type': 'Tarifa 1 - R2',
  'cargo_fijo_unidad': '$/bim.',
  'cargo_fijo': 84.34,
  'cargo_var_unidad': '$/kWh',
  'cargo_var': 0.502},
 {'month': 'month',
  'empresa': 'EDENOR',
  'type': 'Tarifa 1 - R2',
  'cargo_fijo_unidad': '$/bim.',
  'cargo_fijo': 81.16,
  'cargo_var_unidad': '$/kWh',
  'cargo_var': 0.496}]

In [ ]:
data3 = {
    '01-2017': '0E295D74D1F6EEF503258100007403D5',
    '12-2016': 'F3445D62ABDACAF50325810000740207',
    '11-2016': '02AAA1FBEE58DF4D032581000073FF51',
    '10-2016': '5382B612B48FC07E032581000073FE4C',
    '09-2016': '3F43DA5BE61ED68B032581000073FD1A',
    '08-2016': '4FD2174F2E58B221032581000073FB75',
    '07-2016': 'F006DDAA5F3D96EB032581000073FA77',
    '06-2016': '67C580E66A89F871032581000073F8EB',
    '05-2016': 'C35EF31C18D6D5B1032581000070BB18',
    '04-2016': 'E911AA393583946A032581000074075A',
    '03-2016': 'CE4589B52A8D25BC0325810000740622',
    '02-2016': '9F9E646CEEEA456803257F63004D0C33',
    '01-2016': '9D387E66E681520003257F640056D41D'
}

In [ ]:
rows3 = []

for month, code in data3.items():
    url = URL.replace('CODE', code)
    page = pd.read_html(url)

    try:
        rows3.extend(get_rows(page[1].iloc[[0, 7,8], :], month, [2, 3]))
    except:
        print('Error:', month, code)

df3 = pd.DataFrame(rows3)
df3

Error: 02-2016 9F9E646CEEEA456803257F63004D0C33

,month,empresa,type,cargo_fijo_unidad,cargo_fijo,cargo_var_unidad,cargo_var
0,01-2017,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
1,01-2017,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
2,12-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
3,12-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
4,11-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
5,11-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
6,10-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
7,10-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
8,09-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
9,09-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
10,08-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
11,08-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
12,07-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
13,07-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
14,06-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
15,06-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
16,05-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
17,05-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
18,04-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
19,04-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
20,03-2016,EDESUR,Tarifa 1 - R2,$/bim.,84.34,$/kWh,0.502
21,03-2016,EDENOR,Tarifa 1 - R2,$/bim.,81.16,$/kWh,0.496
22,01-2016,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
23,01-2016,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049

In [ ]:
df3.to_csv('file3.csv')

In [ ]:
data4 = {
    '12-2015': '10BA3BDD0C205E8C03257F640056E81A',
    '11-2015': '3EC4B1D80551042903257F640056D1E9',
    '10-2015': '07D74FB7FCE8472903257F030067D7DF',
    '09-2015': '58F95CA2C6962E5703257F030067D4E1',
    '08-2015': 'AE2BCFB3BE59B30D03257F030067D3B8',
    '07-2015': 'F81DD593EC9F6FEF03257F030067CEDB',
    '06-2015': 'B485F275E17D3E1503257F030067D03A',
    '05-2015': 'BF269D21C82C832E03257DD90066C141',
    '04-2015': '8288E2909C27597E03257F030067CB92',
    '03-2015': '8A11B2C21DF8B1A903257F030067DD8D',
    '02-2015': '01F3C4E12E39C3E603257F030067D90A',
    '01-2015': '21CDB8B721EA7E1803257F030067D264',
    '12-2014': 'C535384CC3E0B2F303257DD90066D624',
    '11-2014': 'C8A020F957DF4B2C03257DD90066BE1D',
    '10-2014': '6518885242C80C2103257B580063DDD7',
    '09-2014': '2BC387B8383F5B5903257D80004FBA99',
    '08-2014': '8E28614654B48F6303257D80004FBBDE',
    '07-2014': '1BBD9DF9857A616803257D80004FBCD8',
    '06-2014': 'F0944D558A37839D03257D80004FBDFD',
    '05-2014': 'CD91CA303CDFB9A203257D80004FCA2D',
    '04-2014': 'B348626AFFB7EDFD03257D80004FBEF0',
    '03-2014': '6EF218A51570D45803257D80004FC00F',
    '02-2014': 'C871855DDFECE28903257D80004FC3B6',
    '01-2014': 'DFFF717FA1E97B0E03257D80004FB997',
 }

In [ ]:
rows4 = []

for month, code in data4.items():
    url = URL.replace('CODE', code)
    page = pd.read_html(url)

    try:
        rows4.extend(get_rows(page[1].iloc[[0, 7,8], :], month, [2, 3]))
    except:
        print('Error:', month, code)

df4 = pd.DataFrame(rows4)
df4

,month,empresa,type,cargo_fijo_unidad,cargo_fijo,cargo_var_unidad,cargo_var
0,12-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
1,12-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
2,11-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
3,11-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
4,10-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
5,10-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
6,09-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
7,09-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
8,08-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
9,08-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
10,07-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
11,07-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
12,06-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
13,06-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
14,05-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
15,05-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
16,04-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
17,04-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
18,03-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
19,03-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
20,02-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
21,02-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
22,01-2015,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
23,01-2015,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
24,12-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
25,12-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
26,11-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
27,11-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
28,10-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
29,10-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
30,09-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
31,09-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
32,08-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
33,08-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
34,07-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
35,07-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
36,06-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
37,06-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
38,05-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
39,05-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
40,04-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
41,04-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
42,03-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
43,03-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
44,02-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
45,02-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049
46,01-2014,EDESUR,Tarifa 1 - R2,$/bim.,20.35,$/kWh,0.048
47,01-2014,EDENOR,Tarifa 1 - R2,$/bim.,21.59,$/kWh,0.049

In [ ]:
df4.to_csv('file4.csv')